spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME_DEV}
    password: ${SPRING_DATASOURCE_PASSWORD_DEV}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET_DEV}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

logging:
  level:
    root: INFO
    com.soar_be: DEBUG
