spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_DEV:jdbc:mysql://localhost:3306/mixology?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME_DEV:root}
    password: ${SPRING_DATASOURCE_PASSWORD_DEV:0000}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET_DEV:mixology-jwt-secret-key-for-development-environment-must-be-at-least-256-bits-long-for-HS256-algorithm}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

logging:
  level:
    root: INFO
    com.soar_be: DEBUG
